
// This file has been generated by the GUI designer. Do not modify.
namespace Facturaciòn
{
	public partial class Factura
	{
		private global::Gtk.Fixed fixed5;

		private global::Gtk.HSeparator hseparator3;

		private global::Gtk.Entry entry4;

		private global::Gtk.Label label11;

		private global::Gtk.Label label14;

		private global::Gtk.Label label15;

		private global::Gtk.Entry entry8;

		private global::Gtk.Entry entry7;

		private global::Gtk.Label label17;

		private global::Gtk.Entry entry10;

		private global::Gtk.Entry entry9;

		private global::Gtk.Label label16;

		private global::Gtk.Label label18;

		private global::Gtk.Entry entry11;

		private global::Gtk.Label label19;

		private global::Gtk.VBox vbox2;

		private global::Gtk.RadioButton radiobutton2;

		private global::Gtk.RadioButton radiobutton3;

		private global::Gtk.Entry entry12;

		private global::Gtk.Entry entry13;

		private global::Gtk.Entry entry14;

		private global::Gtk.Entry entry15;

		private global::Gtk.Label label20;

		private global::Gtk.Label label21;

		private global::Gtk.Label label22;

		private global::Gtk.Label label23;

		private global::Gtk.Frame frame2;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.Table table1;

		private global::Gtk.Label label1;

		private global::Gtk.Label label2;

		private global::Gtk.Label label3;

		private global::Gtk.Button btnEditar;

		private global::Gtk.Button button2;

		private global::Gtk.Button button3;

		private global::Gtk.Entry entry6;

		private global::Gtk.Label label13;

		private global::Gtk.Entry entry5;

		private global::Gtk.Label label12;

		private global::Gtk.Image image4;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Facturaciòn.Factura
			this.WidthRequest = 100;
			this.HeightRequest = 100;
			this.Name = "Facturaciòn.Factura";
			this.Title = global::Mono.Unix.Catalog.GetString("Factura");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Facturaciòn.Factura.Gtk.Container+ContainerChild
			this.fixed5 = new global::Gtk.Fixed();
			this.fixed5.Name = "fixed5";
			this.fixed5.HasWindow = false;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.hseparator3 = new global::Gtk.HSeparator();
			this.hseparator3.WidthRequest = 700;
			this.hseparator3.Name = "hseparator3";
			this.fixed5.Add(this.hseparator3);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.hseparator3]));
			w1.X = 13;
			w1.Y = 58;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.entry4 = new global::Gtk.Entry();
			this.entry4.CanFocus = true;
			this.entry4.Name = "entry4";
			this.entry4.IsEditable = true;
			this.entry4.InvisibleChar = '•';
			this.fixed5.Add(this.entry4);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.entry4]));
			w2.X = 73;
			w2.Y = 13;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label11 = new global::Gtk.Label();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Fecha");
			this.fixed5.Add(this.label11);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.label11]));
			w3.X = 27;
			w3.Y = 18;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label14 = new global::Gtk.Label();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Producto ID");
			this.fixed5.Add(this.label14);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.label14]));
			w4.X = 17;
			w4.Y = 114;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label15 = new global::Gtk.Label();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre Producto");
			this.fixed5.Add(this.label15);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.label15]));
			w5.X = 14;
			w5.Y = 161;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.entry8 = new global::Gtk.Entry();
			this.entry8.CanFocus = true;
			this.entry8.Name = "entry8";
			this.entry8.IsEditable = true;
			this.entry8.InvisibleChar = '•';
			this.fixed5.Add(this.entry8);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.entry8]));
			w6.X = 142;
			w6.Y = 156;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.entry7 = new global::Gtk.Entry();
			this.entry7.CanFocus = true;
			this.entry7.Name = "entry7";
			this.entry7.IsEditable = true;
			this.entry7.InvisibleChar = '•';
			this.fixed5.Add(this.entry7);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.entry7]));
			w7.X = 142;
			w7.Y = 111;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label17 = new global::Gtk.Label();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("Precio Regular");
			this.fixed5.Add(this.label17);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.label17]));
			w8.X = 345;
			w8.Y = 160;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.entry10 = new global::Gtk.Entry();
			this.entry10.WidthRequest = 80;
			this.entry10.CanFocus = true;
			this.entry10.Name = "entry10";
			this.entry10.IsEditable = true;
			this.entry10.InvisibleChar = '•';
			this.fixed5.Add(this.entry10);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.entry10]));
			w9.X = 449;
			w9.Y = 155;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.entry9 = new global::Gtk.Entry();
			this.entry9.WidthRequest = 80;
			this.entry9.CanFocus = true;
			this.entry9.Name = "entry9";
			this.entry9.IsEditable = true;
			this.entry9.InvisibleChar = '•';
			this.fixed5.Add(this.entry9);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.entry9]));
			w10.X = 447;
			w10.Y = 114;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label16 = new global::Gtk.Label();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString("Cantidad");
			this.fixed5.Add(this.label16);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.label16]));
			w11.X = 360;
			w11.Y = 118;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label18 = new global::Gtk.Label();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString("Descuento");
			this.fixed5.Add(this.label18);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.label18]));
			w12.X = 359;
			w12.Y = 200;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.entry11 = new global::Gtk.Entry();
			this.entry11.WidthRequest = 80;
			this.entry11.CanFocus = true;
			this.entry11.Name = "entry11";
			this.entry11.IsEditable = true;
			this.entry11.InvisibleChar = '•';
			this.fixed5.Add(this.entry11);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.entry11]));
			w13.X = 448;
			w13.Y = 199;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label19 = new global::Gtk.Label();
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString("Tipo de pago");
			this.fixed5.Add(this.label19);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.label19]));
			w14.X = 573;
			w14.Y = 119;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.WidthRequest = 100;
			this.vbox2.HeightRequest = 100;
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.radiobutton2 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Efectivo"));
			this.radiobutton2.CanFocus = true;
			this.radiobutton2.Name = "radiobutton2";
			this.radiobutton2.DrawIndicator = true;
			this.radiobutton2.UseUnderline = true;
			this.radiobutton2.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.vbox2.Add(this.radiobutton2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.radiobutton2]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.radiobutton3 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Tarjeta"));
			this.radiobutton3.CanFocus = true;
			this.radiobutton3.Name = "radiobutton3";
			this.radiobutton3.DrawIndicator = true;
			this.radiobutton3.UseUnderline = true;
			this.radiobutton3.Group = this.radiobutton2.Group;
			this.vbox2.Add(this.radiobutton3);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.radiobutton3]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			this.fixed5.Add(this.vbox2);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.vbox2]));
			w17.X = 573;
			w17.Y = 152;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.entry12 = new global::Gtk.Entry();
			this.entry12.WidthRequest = 120;
			this.entry12.CanFocus = true;
			this.entry12.Name = "entry12";
			this.entry12.IsEditable = true;
			this.entry12.InvisibleChar = '•';
			this.fixed5.Add(this.entry12);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.entry12]));
			w18.X = 321;
			w18.Y = 252;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.entry13 = new global::Gtk.Entry();
			this.entry13.WidthRequest = 120;
			this.entry13.CanFocus = true;
			this.entry13.Name = "entry13";
			this.entry13.IsEditable = true;
			this.entry13.InvisibleChar = '•';
			this.fixed5.Add(this.entry13);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.entry13]));
			w19.X = 322;
			w19.Y = 295;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.entry14 = new global::Gtk.Entry();
			this.entry14.WidthRequest = 120;
			this.entry14.CanFocus = true;
			this.entry14.Name = "entry14";
			this.entry14.IsEditable = true;
			this.entry14.InvisibleChar = '•';
			this.fixed5.Add(this.entry14);
			global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.entry14]));
			w20.X = 321;
			w20.Y = 339;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.entry15 = new global::Gtk.Entry();
			this.entry15.WidthRequest = 120;
			this.entry15.CanFocus = true;
			this.entry15.Name = "entry15";
			this.entry15.IsEditable = true;
			this.entry15.InvisibleChar = '•';
			this.fixed5.Add(this.entry15);
			global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.entry15]));
			w21.X = 321;
			w21.Y = 383;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label20 = new global::Gtk.Label();
			this.label20.Name = "label20";
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString("SubTotal:");
			this.fixed5.Add(this.label20);
			global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.label20]));
			w22.X = 241;
			w22.Y = 258;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label21 = new global::Gtk.Label();
			this.label21.Name = "label21";
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString("IVA: ");
			this.fixed5.Add(this.label21);
			global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.label21]));
			w23.X = 266;
			w23.Y = 301;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label22 = new global::Gtk.Label();
			this.label22.Name = "label22";
			this.label22.LabelProp = global::Mono.Unix.Catalog.GetString("Total:");
			this.fixed5.Add(this.label22);
			global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.label22]));
			w24.X = 265;
			w24.Y = 345;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label23 = new global::Gtk.Label();
			this.label23.Name = "label23";
			this.label23.LabelProp = global::Mono.Unix.Catalog.GetString("Cambio: ");
			this.fixed5.Add(this.label23);
			global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.label23]));
			w25.X = 247;
			w25.Y = 389;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.frame2 = new global::Gtk.Frame();
			this.frame2.WidthRequest = 630;
			this.frame2.HeightRequest = 250;
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table(((uint)(4)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label();
			this.label1.WidthRequest = 100;
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Verificaciòn");
			this.table1.Add(this.label1);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table1[this.label1]));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label();
			this.label2.WidthRequest = 250;
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Producto ID");
			this.table1.Add(this.label2);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table1[this.label2]));
			w27.LeftAttach = ((uint)(1));
			w27.RightAttach = ((uint)(2));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label();
			this.label3.WidthRequest = 250;
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre Producto");
			this.table1.Add(this.label3);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table1[this.label3]));
			w28.LeftAttach = ((uint)(2));
			w28.RightAttach = ((uint)(3));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment.Add(this.table1);
			this.frame2.Add(this.GtkAlignment);
			this.fixed5.Add(this.frame2);
			global::Gtk.Fixed.FixedChild w31 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.frame2]));
			w31.X = 50;
			w31.Y = 445;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.btnEditar = new global::Gtk.Button();
			this.btnEditar.CanFocus = true;
			this.btnEditar.Name = "btnEditar";
			this.btnEditar.UseUnderline = true;
			this.btnEditar.Label = global::Mono.Unix.Catalog.GetString("_Editar");
			global::Gtk.Image w32 = new global::Gtk.Image();
			w32.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-edit", global::Gtk.IconSize.Menu);
			this.btnEditar.Image = w32;
			this.fixed5.Add(this.btnEditar);
			global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.btnEditar]));
			w33.X = 79;
			w33.Y = 707;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.button2 = new global::Gtk.Button();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = "Cancelar";
			global::Gtk.Image w34 = new global::Gtk.Image();
			w34.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-cancel", global::Gtk.IconSize.LargeToolbar);
			this.button2.Image = w34;
			this.fixed5.Add(this.button2);
			global::Gtk.Fixed.FixedChild w35 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.button2]));
			w35.X = 492;
			w35.Y = 704;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.button3 = new global::Gtk.Button();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = global::Mono.Unix.Catalog.GetString("Imprimir");
			global::Gtk.Image w36 = new global::Gtk.Image();
			w36.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-apply", global::Gtk.IconSize.Menu);
			this.button3.Image = w36;
			this.fixed5.Add(this.button3);
			global::Gtk.Fixed.FixedChild w37 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.button3]));
			w37.X = 589;
			w37.Y = 702;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.entry6 = new global::Gtk.Entry();
			this.entry6.WidthRequest = 50;
			this.entry6.CanFocus = true;
			this.entry6.Name = "entry6";
			this.entry6.IsEditable = true;
			this.entry6.InvisibleChar = '•';
			this.fixed5.Add(this.entry6);
			global::Gtk.Fixed.FixedChild w38 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.entry6]));
			w38.X = 629;
			w38.Y = 14;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label13 = new global::Gtk.Label();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("NO.");
			this.fixed5.Add(this.label13);
			global::Gtk.Fixed.FixedChild w39 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.label13]));
			w39.X = 596;
			w39.Y = 19;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.entry5 = new global::Gtk.Entry();
			this.entry5.CanFocus = true;
			this.entry5.Name = "entry5";
			this.entry5.IsEditable = true;
			this.entry5.InvisibleChar = '•';
			this.fixed5.Add(this.entry5);
			global::Gtk.Fixed.FixedChild w40 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.entry5]));
			w40.X = 395;
			w40.Y = 15;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.label12 = new global::Gtk.Label();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Empleado ID:");
			this.fixed5.Add(this.label12);
			global::Gtk.Fixed.FixedChild w41 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.label12]));
			w41.X = 302;
			w41.Y = 20;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.image4 = new global::Gtk.Image();
			this.image4.Name = "image4";
			this.image4.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "stock_person", global::Gtk.IconSize.Dnd);
			this.fixed5.Add(this.image4);
			global::Gtk.Fixed.FixedChild w42 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.image4]));
			w42.X = 265;
			w42.Y = 14;
			this.Add(this.fixed5);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 728;
			this.DefaultHeight = 750;
			this.Show();
		}
	}
}
