
// This file has been generated by the GUI designer. Do not modify.
namespace Facturaciòn
{
	public partial class Inicio
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.HSeparator hseparator2;

		private global::Gtk.Label label4;

		private global::Gtk.Label label5;

		private global::Gtk.ComboBoxEntry comboboxentry1;

		private global::Gtk.Entry entry1;

		private global::Gtk.Entry entry2;

		private global::Gtk.Image image5;

		private global::Gtk.Image image6;

		private global::Gtk.Entry entry3;

		private global::Gtk.Button button6;

		private global::Gtk.Image image7;

		private global::Gtk.Button button4;

		private global::Gtk.Image image8;

		private global::Gtk.Button button5;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Facturaciòn.Inicio
			this.Name = "Facturaciòn.Inicio";
			this.Title = global::Mono.Unix.Catalog.GetString("Inicio");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Facturaciòn.Inicio.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.hseparator2 = new global::Gtk.HSeparator();
			this.hseparator2.WidthRequest = 530;
			this.hseparator2.Name = "hseparator2";
			this.fixed1.Add(this.hseparator2);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.hseparator2]));
			w1.X = 9;
			w1.Y = 23;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Inicio Sesiòn");
			this.fixed1.Add(this.label4);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label4]));
			w2.X = 34;
			w2.Y = 5;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Rol de Usuario");
			this.fixed1.Add(this.label5);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label5]));
			w3.X = 44;
			w3.Y = 55;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.comboboxentry1 = global::Gtk.ComboBoxEntry.NewText();
			this.comboboxentry1.WidthRequest = 150;
			this.comboboxentry1.Name = "comboboxentry1";
			this.fixed1.Add(this.comboboxentry1);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.comboboxentry1]));
			w4.X = 151;
			w4.Y = 47;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry1 = new global::Gtk.Entry();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '•';
			this.fixed1.Add(this.entry1);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry1]));
			w5.X = 86;
			w5.Y = 125;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry2 = new global::Gtk.Entry();
			this.entry2.CanFocus = true;
			this.entry2.Name = "entry2";
			this.entry2.IsEditable = true;
			this.entry2.InvisibleChar = '•';
			this.fixed1.Add(this.entry2);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry2]));
			w6.X = 324;
			w6.Y = 124;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.image5 = new global::Gtk.Image();
			this.image5.Name = "image5";
			this.image5.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "stock_person", global::Gtk.IconSize.Dialog);
			this.fixed1.Add(this.image5);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.image5]));
			w7.X = 32;
			w7.Y = 115;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.image6 = new global::Gtk.Image();
			this.image6.Name = "image6";
			this.image6.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "stock_keyring", global::Gtk.IconSize.Dialog);
			this.fixed1.Add(this.image6);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.image6]));
			w8.X = 268;
			w8.Y = 116;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry3 = new global::Gtk.Entry();
			this.entry3.WidthRequest = 130;
			this.entry3.CanFocus = true;
			this.entry3.Name = "entry3";
			this.entry3.IsEditable = true;
			this.entry3.InvisibleChar = '•';
			this.fixed1.Add(this.entry3);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry3]));
			w9.X = 354;
			w9.Y = 47;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button6 = new global::Gtk.Button();
			this.button6.WidthRequest = 200;
			this.button6.CanFocus = true;
			this.button6.Name = "button6";
			this.button6.UseUnderline = true;
			this.button6.Label = global::Mono.Unix.Catalog.GetString("Olvide mi contraseña");
			this.fixed1.Add(this.button6);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button6]));
			w10.X = 185;
			w10.Y = 254;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.image7 = new global::Gtk.Image();
			this.image7.Name = "image7";
			this.image7.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-apply", global::Gtk.IconSize.LargeToolbar);
			this.fixed1.Add(this.image7);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.image7]));
			w11.X = 81;
			w11.Y = 210;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button4 = new global::Gtk.Button();
			this.button4.WidthRequest = 150;
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			this.button4.UseUnderline = true;
			this.button4.Label = global::Mono.Unix.Catalog.GetString("Entrar");
			this.fixed1.Add(this.button4);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button4]));
			w12.X = 111;
			w12.Y = 204;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.image8 = new global::Gtk.Image();
			this.image8.Name = "image8";
			this.image8.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-cancel", global::Gtk.IconSize.LargeToolbar);
			this.fixed1.Add(this.image8);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.image8]));
			w13.X = 299;
			w13.Y = 205;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button5 = new global::Gtk.Button();
			this.button5.WidthRequest = 150;
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			this.button5.UseUnderline = true;
			this.button5.Label = global::Mono.Unix.Catalog.GetString("Cancelar");
			this.fixed1.Add(this.button5);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button5]));
			w14.X = 342;
			w14.Y = 199;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 545;
			this.DefaultHeight = 303;
			this.Show();
		}
	}
}
